server:
  port: 8080
  servlet:
    session:
      timeout: 2592000s
      cookie:
        same-site: None
        http-only: true
        secure: true

mode: ${MODE:test}

spring:
  security:
    ignore:
      ssl:
        validation: true
  output:
    ansi:
      enabled: always
session:
  check: ${SESSION_CHECK:true}
top:
  count: ${TOP_COUNT:10}

elasticsearch:
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:elasticstack}
  uris: ${ELASTICSEARCH_URIS:https://10.0.3.254:30018}
  indexname: ${ELASTICSEARCH_INDEX_NAME:cj-log}
grafana:
  host: ${GRAFANA_HOST:http://10.0.1.205:3000}


message:
  source:
    basename: i18n/message-kr

cors:
  allowed-origins: ${CORS_URI:http://10.0.3.254:31824,http://localhost:6001,https://jayutest.best:13006,http://jayutest.best:3249,http://10.0.1.204:3249}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

logging:
  level:
    root: ERROR
    org:
      springframework: ERROR
      elasticsearch: ERROR
